# .github/workflows/process-invoices.yml
name: Procesar Facturas Pendientes

on:
  schedule:
    - cron: '*/15 * * * *'  # Cada 15 minutos

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Procesar facturas pendientes
        run: |
          curl -X POST ${{ secrets.API_URL }}/api/admin/jobs/process-pending-invoices \
            -H "Authorization: Bearer ${{ secrets.ADMIN_TOKEN }}"